
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-07T05:34:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c048ef3e1b38982cf06410887244435d233a28c1",
 "version": "1.17.1.post0.dev56"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
