
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-07T09:47:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b194eede03473ababf3a86d4e008e0ae2a186600",
 "version": "0.4.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
