__title__ = "Treer"
__description__ = "Ascii Tree Creator for Python!"
__url__ = "https://github.com/nagataaaas/Treer"
__version_info__ = ("0", "1", "0")
__version__ = ".".join(__version_info__)
__author__ = "Yamato Nagata"
__author_email__ = "nagata@mail.nagata.pro"
__maintainer__ = "Yamato Nagata"
__license__ = "MIT"
__copyright__ = "(c) 2022 by Yamato Nagata"
