
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-05T09:48:47-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "abeb7a352971c2bf34ff070e1438fcf2d6fac2ce",
 "version": "4.1.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
