# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: systemathics/apis/type/shared/v1/stream.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-systemathics/apis/type/shared/v1/stream.proto\x12 systemathics.apis.type.shared.v1*Z\n\x06Stream\x12\x16\n\x12STREAM_UNSPECIFIED\x10\x00\x12\x16\n\x12STREAM_FIELDS_ONLY\x10\x01\x12 \n\x1cSTREAM_MARKETBOOK_AND_FIELDS\x10\x02\x62\x06proto3')

_STREAM = DESCRIPTOR.enum_types_by_name['Stream']
Stream = enum_type_wrapper.EnumTypeWrapper(_STREAM)
STREAM_UNSPECIFIED = 0
STREAM_FIELDS_ONLY = 1
STREAM_MARKETBOOK_AND_FIELDS = 2


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STREAM._serialized_start=83
  _STREAM._serialized_end=173
# @@protoc_insertion_point(module_scope)
