SYNC_BYTE = bytes([0xfa])
HIRATE_START_BYTE = bytes([0x00])
SIP_START_BYTE = bytes([0x10])
SIP_END_BYTE = bytes([0x03])
TEST_START_BYTE = bytes([0x17])

GPS_POSITION_MESSAGE = bytes([0x10])
GPS_TIME_MESSAGE = bytes([0x11])
MKS_PRESSURE_MESSAGE = bytes([0x12])
SCIENCE_DATA_REQUEST_MESSAGE = bytes([0x13])
SCIENCE_COMMAND_MESSAGE = bytes([0x14])
VALID_SIP_IDS = [GPS_POSITION_MESSAGE,
                 GPS_TIME_MESSAGE,
                 MKS_PRESSURE_MESSAGE,
                 SCIENCE_COMMAND_MESSAGE,
                 SCIENCE_DATA_REQUEST_MESSAGE]

GPS_POSITION_FORMAT = '<2B3fHB'
GPS_TIME_FORMAT = '<2BfHffB'
MKS_PRESSURE_FORMAT = '<2B3HB'
