
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-10T16:20:01-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "85fa86d9a716651aee70831e5bb8f69cc9566eed",
 "version": "2.14.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
