# __version__.py
# autogenerated by poetry-hooks 0.1.0

__version__ = "1.0.2"
__title__ = "jdv_funcutils"
__authors__ = ["Justin Vrana <justin.vrana@justbiotherapeutics.com>"]
__repository__ = ""
__homepage__ = ""
__description__ = ""
__maintainers__ = ""
__readme__ = ""
__license__ = ""
