
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-07T12:40:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9ee2f9991fdcf8b3322d5467fa4e0742a5d3205e",
 "version": "v0.1.38"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
