
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-05T18:30:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "66a3ebf51be2d5712d064a9f4e2f64ea6221861f",
 "version": "1.17.1.post0.dev14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
