# This file automatically generated by
#    /Users/couchbase/jenkins/workspace/python/sdk/python-scripted-build-pipeline/py-client/./couchbase_version.py
# at
#    2022-09-08 14:17:15.489660
__version__ = '4.0.4rc1'