VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('08')
VERSION_HOUR = int('09')
VERSION_MINUTE = int('05')
MAJOR_VERSION = 0
MINOR_VERSION = 9
PATCH_VERSION = 202209080905
version_date = '2022/09/08 09:05'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
