
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-09T10:20:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "32f00bd7c2c8bb4bf7307f37e88e758741e0ed8e",
 "version": "v2.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
