
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-05T16:54:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4f34c9b3f996ca3c4bc662002f0dcdd9b7048ef6",
 "version": "0.7.1.post.dev754"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
