VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('07')
VERSION_HOUR = int('02')
VERSION_MINUTE = int('54')
MAJOR_VERSION = 0
MINOR_VERSION = 9
PATCH_VERSION = 202209070254
version_date = '2022/09/07 02:54'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
