VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('09')
VERSION_HOUR = int('13')
VERSION_MINUTE = int('39')
MAJOR_VERSION = 0
MINOR_VERSION = 10
PATCH_VERSION = 202209091339
version_date = '2022/09/09 13:39'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
