__author__ = "Olli Paloviita"
__email__ = "olli.paloviita@gmail.com"
__license__ = "BSD"
__summary__ = "Jeremy Lainé's aiortc library with only datachannel support and no extra dependencies"
__title__ = "aiortc-datachannel-only"
__uri__ = "https://github.com/ollipal/aiortc-datachannel-only"
__version__ = "1.3.2post3"
