
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-05T16:54:01+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4703f90c1a53f9583db41982ac359cd9a2c6bdb5",
 "version": "1.17.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
