
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-09T03:24:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8dde163d8d0cec8f4b28740a8107844d739b5fa9",
 "version": "1.17.1.post0.dev81"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
