VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('08')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('09')
MAJOR_VERSION = 0
MINOR_VERSION = 10
PATCH_VERSION = 202209081109
version_date = '2022/09/08 11:09'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
