
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-01T09:26:41+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "5078154790273940ff22d4bda59afadd9fb3859d",
 "version": "1.5.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
