
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-03T19:35:37-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "16e4e34e963fbbb96a779055d3ebafa4dbade6fe",
 "version": "1.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
