"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import layerapi.api.ids_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Label(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    name: typing.Text
    @property
    def project_id(self) -> api.ids_pb2.ProjectId: ...
    def __init__(self,
        *,
        name: typing.Text = ...,
        project_id: typing.Optional[api.ids_pb2.ProjectId] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["project_id",b"project_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","project_id",b"project_id"]) -> None: ...
global___Label = Label
