
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-07T06:56:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8fda2ed26c336e9a6063f553f9ec989da408727d",
 "version": "1.17.1.post0.dev68"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
