
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-09-09T15:03:39-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "a6b9eac7dad31d433af3bd71ca90fcb044187d64",
 "version": "v0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
