
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-08-17T10:21:23-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9860cad03146349e051ec7974af45379328a4b33",
 "version": "v22.08.00a220905"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
