# coding: utf-8

"""
    Cloud Application Security API

    Imperva provides customers and partners with the ability to manage accounts and sites via an API. For more information, see <a style=\"text-decoration:none\" href=\"https://docs.imperva.com/bundle/cloud-application-security/page/api/api.htm\">Cloud Application Security API Reference</a>.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_ofinline_response20022 import OneOfinlineResponse20022  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfinlineResponse20022(unittest.TestCase):
    """OneOfinlineResponse20022 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfinlineResponse20022(self):
        """Test OneOfinlineResponse20022"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_ofinline_response20022.OneOfinlineResponse20022()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
