VERSION_YEAR = 2022
VERSION_MONTH = int('09')
VERSION_DAY = int('09')
VERSION_HOUR = int('17')
VERSION_MINUTE = int('13')
MAJOR_VERSION = 0
MINOR_VERSION = 11
PATCH_VERSION = 202209091713
version_date = '2022/09/09 17:13'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
