# PAYMENT STATUS
CONFIRMED_STATUS = 'CONFIRMED'

# FIAT CURRENCIES
CURRENCY_AED = 'AED'
CURRENCY_USD = 'USD'
CURRENCY_EUR = 'EUR'
CURRENCY_GBP = 'GBP'

# CRYPTO CURRENCIES
CURRENCY_BTC = 'BTC'
CURRENCY_ETH = 'ETH'
CURRENCY_TRX = 'TRON'
CURRENCY_PALLA_TRC20 = 'PALLA'
CURRENCY_USDT_TRC20 = 'USDT-TRC20'
CURRENCY_USDT_ERC20 = 'USDT-ERC20'
CURRENCY_USDC_ERC20 = 'USDC-ERC20'
CURRENCY_DAI_ERC20 = 'DAI-ERC20'
